version: 2
jobs:
    build:
        docker:
            - image: rpseq/docker-latex
        steps:
            - checkout
            - run:
                name: config
                command: |
                    git config --global user.email "shamboc04@gmail.com"
                    git config --global user.name "typhonshambo"
            - run:
                name: clean
                command: |
                    if [ -f Shambo_Chowdhury_Resume.pdf ]; then rm Shambo_Chowdhury_Resume.pdf; fi
                    if [ -f Shambo_Chowdhury_Resume.png ]; then rm Shambo_Chowdhury_Resume.png; fi
            - run:
                name: makePDF
                command: latexmk -pdf main.tex -jobname=Shambo_Chowdhury_Resume
            - run:
                name: makePNG
                command: convert -density 100 Shambo_Chowdhury_Resume.pdf -quality 90 -flatten Shambo_Chowdhury_Resume.png
            - run:
                name: push
                command: |
                    git add Shambo_Chowdhury_Resume.pdf Shambo_Chowdhury_Resume.png  # Add all generated files
                    git commit -am "Auto-build $CIRCLE_BUILD_NUM [ci skip]"
                    git push
